backup:
  downgrade: null
  enabled: true
  install: null
  mode: incremental
  type: rsync
  uninstall: null
  upgrade: null
boot:
  load_apps: true
disk:
  trim:
    after_upgrade: false
download:
  icons: true
  multithreaded: false
  multithreaded_client: null
gems:
- arch
- appimage
locale: null
memory_cache:
  data_expiration: 3600
  icon_expiration: 300
store_root_password: true
suggestions:
  by_type: 10
  enabled: true
system:
  notifications: true
  single_dependency_checking: false
ui:
  auto_scale: false
  hdpi: true
  qt_style: fusion
  scale_factor: 1.5
  system_theme: true
  table:
    max_displayed: 500
  theme: darcula
  tray:
    default_icon: null
    updates_icon: null
updates:
  ask_for_reboot: true
  check_interval: 30
